name: Deploy Backend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: ~/backend           # adjust if different
    steps:
      - name: Prep SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          script: |
            set -e
            cd ~/backend
            git pull
            npm ci
            pm2 restart server || pm2 start ecosystem.config.js --only api
            pm2 save
